---
title: COM 411
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")

f <- function (x) {formatC(x, format="d", big.mark=',')}
bold <- function(x) {paste('{\\textbf{',x,'}}', sep ='')}
gray <- function(x) {paste('{\\textcolor{gray}{',x,'}}', sep ='')}
wrapify <- function (x) {paste("{", x, "}", sep="")}
p <- function (x) {formatC(x, format='f', digits=1, big.mark=',')}
library(igraph)
library(tidyverse)
```

<style type="text/css">

/* Changes to RevealJS default formatting.

I prefer this style but you can change these to your preferences */

/* This bit lets you do columns */
.container{
  display: flex;
}

.col{
  flex: 1;
}

.reveal section img{
border: none;
background: none;
box-shadow: none;
}

.highlight {
color: LightCoral;
}

.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
text-transform: none;
}

.reveal h1 {
margin-top:200px;
}

div.footnote {
font-size: 40%;
text-align: right;
}

.bg-image{
width: 180px;
}

.reveal .slides section .fragment.fade-in-then-out,
.reveal .slides section .fragment.current-visible {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-out.current-fragment,
  .reveal .slides section .fragment.current-visible.current-fragment {
    opacity: 1;
    visibility: inherit; }

.reveal .slides section .fragment.fade-in-then-semi-out {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-semi-out.visible {
    opacity: 0.5;
    visibility: inherit; }
  .reveal .slides section .fragment.fade-in-then-semi-out.current-fragment {
    opacity: 1;
visibility: inherit; }

</style>


## Today's Dad Joke

My neighbor had the nerve to ring my doorbell at 3 o'clock in the morning.

<span class='fragment'>
Luckily I was still up playing the drums.
</span>


## Why do people form edges?

> - Pyschological explanations
>	- Homophily
>	- Balance theory/triadic closure/transitivity
> - Rational explanations
>	- Social capital
>	  - People seek to fill structural holes and obtain powerful positions in the network
>	- Social exchange theory
>	  - Do the benefits of relationship outweigh the costs?
>	  - What resources does each node have and need?
> - Assumed to operate at the dyad / edge level


## Focus of Activity

> - Partially a pushback against these
>	- Ties are often a function of activities, not dyadic choices


## Moving forward

> - This is a big deal and I support the decision
>	- We should all be taking things seriously and practicing social distancing
>	- Stay home as much as you can and stay safe!
> - It's going to be :(
> - Tentative plan
>	- Video lectures on YouTube
>	- Online office hours
>	- Open book/open note exam (so... hard)
>	- May adjust final project


## Technical challenges

> - LMK privately if you don't have internet access / a computer / etc.
> - Install R/Rstudio on your computer (instructions are on the wiki)
> - Purdue has some options to run it remotely
> - It will be ugly, but we will make this work!


## Visualization Project

> - Dutch school dataset (on wiki)
>	- gender
>	- age
>	- ethnicity
>	- religion
>	- alcohol use

## Assignment

> - In groups of 2-3
>	- Come up with question
>	- Come up with visualization approach

## Over Spring Break

> - Make your visualization a reality in R

## Thanks

> - Stay safe!
