
---
title: COM 411
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: false
    css: ../../libs/custom_css.css
    reveal_plugins: ["notes"]
    lib_dir: ../../libs
---

## Troubled Lands

<iframe width="560" height="315" src="https://www.youtube.com/embed/eIchwB6xJJI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Troubled Lands

> - Video
> - Rules
>	- Talking is fine
>	- No talking/interacting with other groups
>	- Can see other people's cards
>	- Must do one thing each turn
>	- Eroded -> Fallow -> Planted

## Round 1 - Collaborative

> - Group with highest total score wins
> - When done, bring weather cards for me for reshuffling
> - Winner?

## Round 2 - Competitive

> - Person in group with highest score wins
> - When done, bring weather cards for me for reshuffling

## Round 3 - Independent

> - Person of each type with highest score wins


## Take a few minutes to think/write about:

> - How did you play differently in different versions?
> - What in real life is similar to each version of the game?
> - How did you decide whether or not to help others?
> - What does this have to do with social networks and social capital?!


## Debrief

> - What did you think about while playing?
> - How did you feel as you played? Did those feeling change across different versions of the game?
> - When do you help others in real life?

## Debrief

> - Were resources and abilities distributed fairly?
> - How should resources be distributed in the real world?
> - What role did communication play? How did your group make decisions?
> - Did you work to make things equal? Why or why not?
> - What kinds of inequality appeared in the game?

## Debrief

> - Did anyone sanction someone else? Why?
