---
title: Week 12
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: false
    css: ../../libs/custom_css.css
    reveal_plugins: ["notes"]
    lib_dir: ../../libs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")
set.seed(0121)
library(igraph)
library(tidygraph)
library(ggraph)
```

## Today's Dad Joke

When I was young, we were really poor. My family could only afford a second-hand calculator, which was missing the "X" button.

<p class='fragment'>
Times were hard.
</p>

## Housekeeping

> - Self Assessment responses are in
> - Exam
>	- Open book / open note
>	- Begin on Monday, due Thursday
>	- Do your own work
>	- Short essay questions
>	  - 2-4 paragraphs
>	- Visualization / ggraph


## Final Project

> - Timing for final project
>	- Don't wait - get started now!
>	- Reach out if you get stuck
> - Watch the video and use the example data
> - Look at example projects from the past
> - Not all visualizations have to be networks
> - Concepts + Visualizations


## Networks and Technology

> - Social media has made large-scale human networks visible
>	- Degree distributions
>	- Network paths (six degrees of separation)
>	- Communication patterns
>	- Information and belief diffusion

## Social science is being reshaped by online data

> - We can look at thousands or millions of people
> - Starting to answer questions like:
>	- When do people change their minds?
>	- Why do people choose to cooperate?
>	- What predicts participating in a new group?
> - We can finally see global networks instead of just small portions

## But, there are some important caveats

> - Technology doesn't only record interactions, it shapes them
>	- Is this true of people, or true of Facebook/Reddit/Twitter?
> - Human systems respond to observation and evolve
> - Much is unobserved
>	- These are often "thin slices"
>	- In what other ways are people communicating?
>	- What other technologies or circumstances shape their behavior?

## Those who understand networks have an advantage

> - Advertisers, activists, and politicians who understand network principles like homophily, clustering, and complex contagion will see their messages spread farther and faster.

