---
title: COM 411
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: true
    css: ../../libs/custom_css.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = './')
#source("resources/preamble.R")
library(igraph)
library(tidygraph)
library(ggraph)
```


## Today's Dad Joke

My neighbor had the nerve to ring my doorbell at 3 o'clock in the morning.

<span class='fragment'>
Luckily I was still up playing the drums.
</span>


## Housekeeping

> - Self Assessment Reflections
>	- Goals for the class
>	- Feedback for me
> - Afterward, I will
>	- Report on participation
>	- Review your HW
>	- Review your discussion questions
> - Discussion questions
>	- People aren't doing them. Move to Discord? Brightspace?
>	- Better way to meet goals of reading + thinking about readings?


## Discussion Questions

> - What is centralization?
> - When is a centralized network better?
> - What is "transactive memory"
> - According to the Informal Networks article, why is it important to identify different kinds of networks?
> - What sorts of information can be learned from an advice network?
>	- A trust network?
> - Have you thought about the groups that you are in from a network perspective? What insights have you had?



## Homework review


## Thursday

> - Small group simulations/activities
> - R Help
