---
title: "Week 3: How are communication networks formed?"
date: "2024-09-03"
---

### Tuesday

**Assignment Due (on Monday):**

* [Reading Review Assignments](/syllabus/syllabus.qmd#reading-review-assignments)


**Readings:** 

* Feld, S. L. (1981). [The focused organization of social ties](https://www.jstor.org/stable/2778746). American Journal of Sociology, 86(5), 1015–1035.
* McPherson, M., Smith-Lovin, L., & Cook, J. M. (2001). [Birds of a Feather: Homophily in Social Networks](https://www-jstor-org.ezproxy.lib.purdue.edu/stable/2678628). Annual Review of Sociology, 27, 415–444.
* [Optional] Monge, P. R., & Contractor, N. S. (2003). Theories of communication networks. Oxford, UK: Oxford University Press. (pp. 298–314) - On Brightspace under Content > Readings

*Note:* This week involves reading two academic articles. [Read this](/syllabus/syllabus.qmd#Reading_Academic_Articles) to understand my expectations and some tips for reading and understanding these articles. [This video](https://www.youtube.com/watch?v=IX8eGg_7gF4) goes over how you can use Claude.ai to understand papers better.

**Lecture Video:**


* Tie Formation [14:55]

{{< video https://youtu.be/bwgd7gIAvb4 >}}

* Slides

<iframe class='slide-deck' src="/lectures/content_lectures/tie_formation.html"> </iframe>

**Concepts:**

* Exposure, formation, maintenance, decay
* Homophily
* Reciprocity
* Triadic closure

<!--
**Class Slides:**

* Class Slides

<iframe class='slide-deck' src='/lectures/class_lectures/week_3.html"/>

-->

### Thursday

**Supplementary R lectures (watch before class):**

* Why R + Programming principles lecture [12:53]

{{< video https://youtu.be/6ThBHfg3Dh0 >}} 

**Class Schedule:**

* [R Lab 2 - Creating Networks](/assignments/r_lab_2_%E2%80%93_creating_networks.qmd)
