---
title: "Week 11: Communities and Core-periphery"
date: "2024-10-29"
---

### Tuesday

**Assignment Due:**

* [Reading Review](/syllabus/syllabus.qmd#reading-review-assignments)
* Submit two exam questions on Brightspace
* [Visualization Challenge](Visualization-Challenge)
* Sign up for a Self Reflection Discussion [on my calendar](https://app.simplymeet.me/jeremy-foote/15min)
  * Must happen before November 5th
  * Please prioritize office hours (Tuesdays from 2-4)

**Video Lecture:**

* [Communities and Core-periphery](https://youtu.be/7pQMUisgv1U) [23:15] [Slides](https://jeremydfoote.com/Communication-and-Social-Networks/week_11/lecture/communities_in_networks.html)

**Readings:**

* Girvan, M., & Newman, M. E. (2002). [Community structure in social and biological networks](https://www.pnas.org/content/pnas/99/12/7821.full.pdf). Proceedings of the National Academy of Sciences.
* Barberá, P., Wang, N., Bonneau, R., Jost, J. T., Nagler, J., Tucker, J., & González-Bailón, S. (2015). [The critical periphery in the growth of social protests](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0143611). PLoS ONE.
  * [Claude.ai Summary](Barbera-summary)
* (Optional) Hanneman, R. A., & Riddle, M. (2005). [Cliques and sub-groups](http://faculty.ucr.edu/~hanneman/nettext/C11_Cliques.html). In Introduction to social network methods. University of California.

### Thursday

**Class Schedule:**

* [R Lab 7 - Finding and visualizing groups in networks](https://github.com/jdfoote/com_and_social_networks_labs/raw/main/lab_7_groups_in_networks.qmd)
