---
pagetitle: Capital and Social Capital
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: false
    css: ../../libs/custom_css.css
    reveal_plugins: ["notes"]
    lib: ../../libs
    allow_uptree_lib_dir: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")
library(igraph)
library(tidygraph)
library(ggraph)
```

# Capital and Social Capital

## Dad Joke

I decided to kill off a few characters in the book I'm writing.

It would definitely spice up my autobiography.

## Housekeeping

> - Social Search assignment (March 8)
>	- Try to find someone with driver's license from HI
>	- No group texts
>	- Diagram search network
>	- Instructions on wiki

## Reading Questions

> - What is capital?
> - What is economic capital?
> - What is cultural capital?
> - What is social capital?

## Reading Questions

> - What is a weak tie?
> - What is the argument for why weak ties are better for finding information?
> - What are strong ties better for?
> - How does a network of strong ties look different from a network with weak ties?

## Reading Questions

> - We can exchange forms of capital for goods, services, or for other kinds of capital.
> - What's an example of exchanging cultural capital for social capital and vice versa.
> - What's an example of exchanging social capital for economic capital and vice versa.
> - What's an example of exchanging economic capital for cultural capital and vice versa.

## Criticism

> - What aspects of the concept of capital and social capital ring true to you? What feels like is missing from this theory?

## Discussion Questions


## Summary

## R Review

