---
title: Final Self-Assessment Reflection
---

Answer the following questions about your learning and participation thus far. Please note that there are a lot of questions. I am not expecting extensive essays for these. Some may be answered in a single sentence, while others may inspire more detail. 


* What have you done to ensure that you understand the material and concepts?
* How have you addressed previous goals, challenges, and/or feedback?
* What have you done to apply the concepts we've been learning to your own experiences?
* What have you learned in this class that you will take with you?
* What obstacles have you overcome?
* What else would you like to share?

Next, I'd like you to look on Brightspace and Discord and review the work you've done, and think about your participation in class. I'd also like you to review the expectations for each grade in this class. 

* Based on your answers above, the work you have done, and the guidelines in the syllabus, what grade would you assign yourself in the class? Why?

Finally, some feedback for me (feel free to submit this at https://forms.gle/ZQbTXHiaqy7WrxFj7 if you'd prefer to be anonymous):

* What did you enjoy about this class?
* What are two ways in which this class could be better?
