---
title: Self-Assessment Reflection
---

Answer the following questions about your learning and participation thus far. Please note that there are a lot of questions. I am not expecting extensive essays for these. Some may be answered in a single sentence, while others may inspire more detail. Remember, also, that the grade you assign here is not some element of a permanent calculation - this is for us to align our expectations and set goals. So, if you absolutely want to earn an A in the class, but you assign yourself a B- for your work thus far, you can absolutely still earn an A by setting and meeting higher goals for the remainder of the course.

1. What have you done to ensure that you understand the material and concepts?
1. How have you addressed challenges and/or feedback?
1. What have you done to apply the concepts we've been learning to your own experiences?
1. How have you used AI in this class (ChatGPT, Claude.AI, etc)?
1. How have you helped others in the class to learn?
1. What is something you could improve on related to the class? 
1. What are your goals for the rest of class?
1. What else would you like to share?
1. What would you like feedback on?
1. Based on your answers above, the work you have done, and the guidelines in the syllabus, what grade would you assign yourself thus far? Why?

Finally, some feedback for me. 

I have learned that feedback is more honest (and therefore more helpful!) if given anonymously, so I would encourage you to [fill out this survey](https://docs.google.com/forms/d/e/1FAIpQLSepkCJfjpC8jlq6Xfq8zq64hEF8SPJF60N5rLSdlRx_BuL_Ag/viewform?usp=sf_link).