---
title: The Resource Game
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: false
    reveal_plugins: ['notes']
    css: .././resources/custom_css.css
    lib_dir: ../../libs
    allow_uptree_lib_dir: True
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = './')
library(tidygraph)
library(ggraph)
```
## Discord signup

https://discord.gg/WSc5J7stgg

## The game

Each of you needs things that other people in the room have. These resources are represented by letters.

However, you are only "friends" with a small number of people. These are the people that you can communicate with, ask for resources, and give resources to.

The goal is to get the resources that you need as quickly as possible.

## Rules

- Only communicate through written messages, to neighbors
- Give resources by sending '$give jdfoote A' to the NetworkGameBot
- If you forget what you have/need, send '$status'
- If you are an observer, send '$status' to get an updated network graph
- You can continue playing after you have all resources, if you want

## How did it go?

>- What worked well?
>- What didn't?
>- Who was fastest? Why?
>- What was the longest path a resource traveled?

## Global network

## Debrief topics to cover
- Degree centrality
- Reciprocity
- Social capital
- Structural holes
- Reputation and deceit
- Position and power
- Multiplexity
- Number vs. type of ties (centrality measures)
- Global/local networks
- Tie maintenance
- Sponsorship
- Norms and social conventions

## Meta discussion
- How does this differ from real-world networks?

- What does this make you see differently?

