---
title: Week 2 - Network Data and Network Types
sort: 2
format: 
  revealjs:
    css: /resources/custom_css.css
    theme: white
    progress: true
    transition: convex
    reveal_plugins: ['notes']
---

## Today's Dad Joke

Shout out to people wondering what the opposite of 'in' is.



## Housekeeping

> - Intro survey
> - Discussion questions
>	- Monday at noon

## Schedule

> - Housekeeping / Announcements (5-10)
> - Discussion and review (35-45)
> - Consolidation and Confusion (10-15)
> - Supplementary lectures
>	- Response to needs
>	- Discuss at end of class


## Review

> - Homework review
>	- Encouragement to be prepared
>	- Time to identify confusion - it's OK to be confused!
> - Discussion questions review


# Homework and Reading Review

## Class Questions

> - What do you want to talk about today?

## Basic Concepts

> - What is a node?
> - What is an edge?
> - What is the "individual" perspective of data and how does it differ from a network perspective?

## Network Representations

```{r, message=F,warning=F,echo=F}
library(igraph)
set.seed(24)
G = erdos.renyi.game(5, .4)
plot(G)
```

> - What is the edgelist of this graph?
> - What is the matrix representation of this graph?

## Questions from homework?

## Discussion Questions

## Consolidation

> - What were some of the key ideas?
> - What are you thinking differently about now?
> - What are remaining questions/confusions?

## Thursday

> - Take ~ an hour to try to install everything, work on R Lab 1
> - Mostly working on R Lab together
