---
title: Week 8
format: 
  revealjs:
    css: ./libs/custom_css.css
    theme: white
    progress: true
    transition: convex
    reveal_plugins: ['notes']
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")
set.seed(0121)
library(igraph)
library(tidygraph)
library(ggraph)
```

## Dad Joke

What is brown and sticky?

<span class='fragment'>
A stick.
</span>

## Housekeeping

> - Social Search assignment
>	- Try to find someone with driver's license from HI
>	- No group texts
>	- Diagram search network
>	- Instructions on wiki

## Also upcoming

> - Visualization Challenge
>	- Start from existing dataset (Dutch school student behavior)
>	- Come up with a question
>	- Create a network visualization that helps to answer that question
>	- Working in pairs is great


## Review Questions

> - What is a "path length"?
> - What is the "geodesic distance" or "diameter" of a network?
> - What is triadic closure?
> - Why would we expect networks with high triadic closure to have high geodesic distance?
> - What was the Travers and Milgram experiment?
> - How can we have such high triadic closure but still have short path lengths? What was the key insight from Watts and Strogatz?

## R Questions


## Discussion Questions


## R Co-working time
