---
pagetitle: Social Capital
format: 
  revealjs:
    css: /resources/custom_css.css
    theme: white
    progress: true
    transition: convex
    reveal_plugins: ['notes']
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")
library(igraph)
library(tidygraph)
library(ggraph)
```


# The Forms of Capital

## What is capital?

> - "Accumulated labor which [...] enables [agents] to appropriate social energy in the form of reified or living labor." - Bourdieu
> - Three types:
>	- Economic
>	- Cultural
>	- Social

## Economic Capital
> - Money
> - Factories
> - Businesses

## Cultural capital

> - Culture, cultivation, assimilation
> - Developing a way of seeing and acting in the world
> - Also education and technical skills
> - Mostly "embodied"

## Social Capital

> - "the aggregate of the actual or potential resources which are linked to possession of a durable network of more or less institutionalized relationships of mutual acquaintance and recognition"
> - Bourdieu describes this as membership in a group
>	- Families
>	- Schools
>	- Parties
>	- Etc.
> - Our social connections can help us to mobilize the capital (cultural and economic) of others


## What is capital for?

> - Some goods are "purchased" with different kinds of labor
>	- E.g., emotional support and friendship
> - For Bourdieu, the goal is to improve and ensure position in social space
> - Capital can be traded for other kinds of capital.
>	- Money + time for education
>	- Gifts -> social capital

## How can we identify when people have social capital?

> - Closure and embeddedness
>	- Strong, dense, networks
>	- Reciprocal, repeated exchanges that encourage cooperation
> - Structural holes
>	- Connecting two groups
>	- Power to control information, gain new information
> - When might one or the other be beneficial?


## Strength of weak ties

>  - One of the most cited social science papers ever (> 55K citations!)
> - Initial question:
>	- How do people find jobs?
> - Survey showed that people found jobs through acquaintances rather than friends

## Strength of weak ties

> - What are the "weak ties" that Granovetter refers to?
> - Why is information more likely to come through weak ties?
>	- Strong ties have redundant information
>	- They are already tied to each other
>	- Weak ties are more likely to access new parts of the network

## Different relationships have different benefits
> - Some types of social capital (cooperation, support, etc.) are best served through dense cliques
> - Others (innovation, information search, etc.) require connecting distant groups (bridges and weak ties)

## Societal level social capital

> - Putnam argues for the idea of generalized social capital
> - Do people trust each other?
> - Societies with trust are more successful.
>	- Trust is a public good
>	- Time, energy, and money can be spent on better things
