---
title: Week 5
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: true
    css: ../../libs/custom_css.css
    lib_dir: ../../libs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")
```

## Dad Joke

Bro, can you pass me that leaflet?

<span class='fragment'>
Brochure.
</span>


## Self Reflections and feedback

> - Thank you so much for being open and honest!
> - Some summary thoughts
>	- Things are going pretty well
>	- R is hard but people are persisting
>	- Readings are not great
> - Cold calling is scary

## My plans for change

> - Try to make more time for small group discussion
>	- A few minutes at the beginning of class
>	- Summaries of readings?
> - Show a few questions at a time so people can prep a bit
> - Start w/o randomization for discussion questions
> - Summarization at end of class

## 

The work and the readings are not easy but based off the grading system I truly feel I learn more in this class than other class. I say that because I get to try to attempt things in class, I am not good at without the fear of doing poorly in this class. So, in a sense I feel confident knowing that I give my all and I am wrong it is ok. I can learn what I did wrong and still be a successful student and learn in a healthy state

## Suggestions for success

> - Keep working on assignments that you missed / got wrong
> - 


## Housekeeping

> - Explanation of why R + fundamentals of R and ggraph videos
> - Videos + readings on centrality and power
> - How do we measure who is important and influential?

## Review

> - What is an "ego network"?
> - What information can we get from an ego network?
> - What information can't we get from an ego network?
> - What is the "cognitive activation" of a network?


## Review

> - What are the benefits of having a dense ego network?
> - What are the benefits of having a sparse ego network?
> - What are some reasons that you think friendship is asymmetrical?
> - Is there such thing as a "true" social network? How could we find it out?
> - What are some ways that our perceptions of a network could influence our behaviors?

## Discussion Questions


## Summary

## Debugging

Strategies when R code doesn't work:

> - Simplify
> - print()
> - Google!
> - Friends

# Ego Network Activity

## What do our ego networks look like?

> - From time to time, most people discuss important matters with other people. Looking back over the last 6 months, who are the people with whom you discussed matters important to you?

## Making Connections

- Make an edgelist for each connection, with tie strength of:
	- Total strangers: 0
	- Especially close: 1
	- In between: .5

## Write attributes of your connections to a node attribute file

 - Sex
 - Education (years of education)
 - Race
 - Age
 - Kin or non-kin (are they related to you?)


## Calculate your statistics

- Network size
- Kin network size
- Nonkin network size
- Density
- Age heterogeneity
- Education heterogeneity
- Race heterogeneity
- Sex heterogeneity (proportion in majority)


## Importing and visualizing in R
