---
title: COM 411
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")

f <- function (x) {formatC(x, format="d", big.mark=',')}
bold <- function(x) {paste('{\\textbf{',x,'}}', sep ='')}
gray <- function(x) {paste('{\\textcolor{gray}{',x,'}}', sep ='')}
wrapify <- function (x) {paste("{", x, "}", sep="")}
p <- function (x) {formatC(x, format='f', digits=1, big.mark=',')}
library(igraph)
```

<style type="text/css">

/* Changes to RevealJS default formatting.

I prefer this style but you can change these to your preferences */

/* This bit lets you do columns */
.container{
  display: flex;
}

.col{
  flex: 1;
}

.reveal section img{
border: none;
background: none;
box-shadow: none;
}

.highlight {
color: LightCoral;
}

.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
text-transform: none;
}

.reveal h1 {
margin-top:200px;
}

div.footnote {
font-size: 40%;
text-align: right;
}

.bg-image{
width: 180px;
}

.reveal .slides section .fragment.fade-in-then-out,
.reveal .slides section .fragment.current-visible {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-out.current-fragment,
  .reveal .slides section .fragment.current-visible.current-fragment {
    opacity: 1;
    visibility: inherit; }

.reveal .slides section .fragment.fade-in-then-semi-out {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-semi-out.visible {
    opacity: 0.5;
    visibility: inherit; }
  .reveal .slides section .fragment.fade-in-then-semi-out.current-fragment {
    opacity: 1;
visibility: inherit; }

</style>

## Today's Dad Joke
To the thief who took my anti-depressants:

<span class='fragment'>
I hope you're happy!
</span>

## Housekeeping

> - Exam review
>	- make_network was confusing
>	- Matrices and edgelists were very well understood
>	- People aren't reading
> - Grading
>	- Hopefully finished in the next few days
>	- Will curve as needed


# The Forms of Capital

## What is capital?

> - "Accumulated labor which [...] enables [agents] to appropriate social energy in the form of reified or living labor." - Bourdieu
> - Three types:
>	- Economic
>	- Cultural
>	- Social

## Cultural capital

> - Culture, cultivation, assimilation
> - Developing a way of seeing and acting in the world
> - Also education and technical skills
> - Mostly "embodied"

## Social Capital

> - "the aggregate of the actual or potential resources which are linked to possession of a durable network of more or less institutionalized relationships of mutual acquaintance and recognition"
> - Bourdieu describes this as membership in a group
>	- Families
>	- Schools
>	- Parties
>	- Etc.
> - Our social connections can help us to mobilize the capital (cultural and economic) of others
> - Some goods are "purchased" with different kinds of labor
>	- E.g., emotional support and friendship
> - For Bourdieu, the goal is to improve and ensure position in social space

## Other views of social capital

> - Closure and embeddedness
>	- Strong, dense, networks
>	- Reciprocal, repeated exchanges that encourage cooperation
> - Structural holes
>	- Connecting two groups
>	- Power to control information, gain new information
> - When might one or the other be beneficial?


## Strength of weak ties

>  - One of the most cited social science papers ever (> 55K citations!)
> - Initial question:
>	- How do people find jobs?
> - Survey showed that people found jobs through acquaintances rather than friends

## Strength of weak ties

> - What are the "weak ties" that Granovetter refers to?
> - Why is information more likely to come through weak ties?
>	- Homogeneity, redundancy, and bridges
> - How does this relate to Six Degrees?
> - Overall summary
>	- Some types of social capital (cooperation, support, etc.) are best served through dense cliques
>	- Others (innovation, information search, etc.) require connecting distant groups (bridges and weak ties)

## Societal level social capital

> - Putnam (in reading for Thursday) argues for the idea of generalized social capital
> - Do people trust each other?
> - Societies with trust are more successful. Why?

## Homework

> - Keep reading about these topics (2 more readings)
