---
title: COM 411
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")

f <- function (x) {formatC(x, format="d", big.mark=',')}
bold <- function(x) {paste('{\\textbf{',x,'}}', sep ='')}
gray <- function(x) {paste('{\\textcolor{gray}{',x,'}}', sep ='')}
wrapify <- function (x) {paste("{", x, "}", sep="")}
p <- function (x) {formatC(x, format='f', digits=1, big.mark=',')}
library(igraph)
library(tidyverse)
```

<style type="text/css">

/* Changes to RevealJS default formatting.

I prefer this style but you can change these to your preferences */

/* This bit lets you do columns */
.container{
  display: flex;
}

.col{
  flex: 1;
}

.reveal section img{
border: none;
background: none;
box-shadow: none;
}

.highlight {
color: LightCoral;
}

.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
text-transform: none;
}

.reveal h1 {
margin-top:200px;
}

div.footnote {
font-size: 40%;
text-align: right;
}

.bg-image{
width: 180px;
}

.reveal .slides section .fragment.fade-in-then-out,
.reveal .slides section .fragment.current-visible {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-out.current-fragment,
  .reveal .slides section .fragment.current-visible.current-fragment {
    opacity: 1;
    visibility: inherit; }

.reveal .slides section .fragment.fade-in-then-semi-out {
  opacity: 0;
  visibility: hidden; }
  .reveal .slides section .fragment.fade-in-then-semi-out.visible {
    opacity: 0.5;
    visibility: inherit; }
  .reveal .slides section .fragment.fade-in-then-semi-out.current-fragment {
    opacity: 1;
visibility: inherit; }

</style>


## Today's Dad Joke

Yesterday I confused the words "jacuzzi" and "Yakuza".

Now I'm in hot water with the Japanese mafia.

## Housekeeping

> - Reading summaries + FlipGrid
> - Final Project

# Networks and Collaboration


## We are surrounded by "collective goods"

> - The whole group shares in the output, independent of their contributions
>	- Parks
>	- Roads
>	- National defense
>	- Lighthouses
>	- Clean air
>	- Group projects

## However, these goods have misaligned Incentives

> - Individual incentive is to do little or nothing
>	- Especially when your contribution will make little difference
> - These goods are typically underproduced, without help


## Collaboration is the great human super power. How do we do it?

> - States or organizations that force people to make the "right" decision
> - Punishment for defection
> - Selective incentives
> - Heterogenous benefits
> - Making coordination and contributions easier


## What do networks have to do with collaboration?

> - People are "embedded" in networks
>	- Defecting has social impacts if they occur in networks
>	- Rumor is a way of promoting cooperation
> - Through networks, people can coordinate
>	- Figure out who knows what (transactive memory)
>	- Building shared understanding of goals (shared mental model)

## Online Collaboration works surprisingly well

> - Wikipedia and open source software often work better than what companies produce
> - Why does it work?
>	- Artifact does a lot of the work of coordinating
>	- Costs of contribution are lower
>	- Internet allows for the identification of people for whom contribution is easy

## The End
