---
title: COM 411
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: false
    css: ../../libs/custom_css.css
    reveal_plugins: ["notes"]
    lib_dir: ../../libs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = './')
source("resources/preamble.R")
set.seed(0121)
library(igraph)
library(tidygraph)
library(ggraph)
```

## Today's Dad Joke

Yesterday I confused the words "jacuzzi" and "Yakuza".

Now I'm in hot water with the Japanese mafia.

## Housekeeping

> - Draft of final project to peers on Thursday
>	- I will make assignments and send a Brightspace + discord announcement
>	- Feedback by next Tuesday


## Plan for today

> - Lecture
> - Summaries
> - Discussion
> - Exam review

# Networks and Collaboration


## We are surrounded by "collective goods"

> - The whole group shares in the output, independent of their contributions
>	- Parks
>	- Roads
>	- National defense
>	- Lighthouses
>	- Clean air
>	- Group projects

## However, these goods have misaligned Incentives

> - Individual incentive is to do little or nothing
>	- Especially when your contribution will make little difference
> - These goods are typically underproduced, without help


## Collaboration is the great human super power. How do we do it?

> - States or organizations that force people to make the "right" decision
> - Punishment for defection
> - Selective incentives
> - Heterogenous benefits


## What do networks have to do with collaboration?

> - People are "embedded" in networks
>	- Defecting has social impacts if they occur in networks
>	- Rumor is a way of promoting cooperation
> - Through networks, people can coordinate
>	- Figure out who knows what (transactive memory)
>	- Building shared understanding of goals (shared mental model)

## Online Collaboration works surprisingly well

> - Wikipedia and open source software often work better than what companies produce
> - Why does it work?
>	- Artifact does a lot of the work of coordinating
>	- Costs of contribution are lower
>	- Internet allows for the identification of people for whom contribution is easy

