---
title: Creating Networks
author: "Jeremy Foote"
date: "1/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# import the libraries needed
library(igraph)
library(ggraph)
library(tidygraph)
```

I'm just going to assign you to three groups -a 
```{r}
## YOUR CODE HERE
chunk2 <- function(x,n) split(x, cut(seq_along(x), n, labels = FALSE)) 
```


## Challenge Exercise

Change the ggraph plot so that it show the names of the students, and make the nodes bigger.

Hint: You will a [geom_node_label](https://ggraph.data-imaginist.com/reference/geom_node_text.html) and the "aesthetics" for [geom_node_point](https://ggraph.data-imaginist.com/reference/geom_node_point.html) may be helpful

```{r}
s = 'Dan
Ethan
Meredith
Brayden
Carly
Liam
Hayley
Roshana
Gracie'
s = str_split(s, '\n')[[1]]

s = sample(s)

x = chunk2(s, 2)
```

```{r}
g1 = make_ring(length(x[[1]]))
V(g1)$name = x[[1]]

#g2 = make_star(length(x[[3]]))
#V(g2)$name = x[[3]]

g3 = make_full_graph(length(x[[2]]))
V(g3)$name = x[[2]]

plot(g1)
#plot(g2)
plot(g3)
```



