
---
title: Troubled Lands Activity
template: "../resources/template.html"
output: 
  revealjs::revealjs_presentation:
    theme: white
    progress: true
    transition: convex
    self_contained: false
    css: .././resources/custom_css.css
    lib: ../../libs
    allow_uptree_lib_dir: true
---

## Troubled Lands Explainer

<iframe width="560" height="315" src="https://www.youtube.com/embed/eIchwB6xJJI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Troubled Lands

> - Rules
>	- Talking is fine
>	- No talking/interacting with other groups
>	- Can see other people's cards
>	- Each person does one thing each turn (before drawing the weather card)
>	- Eroded -> Fallow -> Forest/Fields/Pasture
>   - Weather are 1-10 (plus extra 6,8), sorted randomly
>   - 6/9 are tough to distinguish - make sure raindrops are falling down

## Round 1 - Collaborative

> - 8 turns
> - Group with highest total score wins
> - When done, bring weather cards to me for reshuffling and write your score on the board

## Reminder

- Start with:
  - 6 Forest
  - 2 Fallows
  - 2 Fields
  - 2 Pasture

- Eroded if more rain than forests
  - *2* become eroded
  - Erosion order: Fallows, field, pasture, forest

Can't plant on eroded, have to turn it to fallows first

## Round 2 - Within-group competition

> - 8 turns
> - Person in group with highest score wins
> - When done, bring weather cards to me for reshuffling
> - Write your score and role on the board

## Round 3 - Within-role competition

> - Person of each type with highest score wins


## Take a few minutes to think/write about:

> - How did you play differently in different versions?
> - What in real life is similar to each version of the game?
> - How did you decide whether or not to help others?
> - What does this have to do with social networks and social capital?!


## Debrief

> - What did you think about while playing?
> - How did you feel as you played? Did those feeling change across different versions of the game?
> - When do you help others in real life?

## Debrief

> - Were resources and abilities distributed fairly?
> - How should resources be distributed in the real world?
> - What role did communication play? How did your group make decisions?
> - Did you work to make things equal? Why or why not?
> - What kinds of inequality appeared in the game?

## Debrief

> - Did anyone sanction someone else? Why?
